jobs:
  job_id:
    env: REGION: 'northamerica-northeast1'
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        # Either user Workload Identity Federation or Service Account Keys.

    # This example uses the docker login action
    # Prefer newer Artifact Registry over Container Registry
    - uses: 'docker/login-action@v1'
      with:
        registry: $REGION-docker.pkg.dev
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    # Can remove the depedency on login-action@v1 with the following
    # This example runs "docker login" directly to Artifact Registry.
    #- run: |-
    #    echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://$REGION-docker.pkg.dev

    # This example runs "docker login" directly to Container Registry.
    #- run: |-
    #    echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
